In [28]:
import numpy as np
numbers=np.array([1,2,3,4])

In [29]:
a=numbers

In [34]:
print(id(a))
print(id(numbers))

1488930084528
1488930084528


In [31]:
a[1]=400

In [33]:
a

array([  1, 400,   3,   4])

In [9]:
numbers

array([0, 2, 3, 4])

In [10]:
numbers2=numbers.view()

In [11]:
type(numbers2)

numpy.ndarray

In [12]:
numbers2

array([0, 2, 3, 4])

In [16]:
print(id(numbers))
print(id(numbers2))

1488942473808
1488928655472


In [19]:
numbers[0]=2
numbers

array([2, 2, 3, 4])

In [20]:
numbers2

array([2, 2, 3, 4])